### ISSUE TITLE
Change the repo structure

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-build-classic#23] opened 2017-09-14 11:19 UTC
As agreed in https://github.com/ckeditor/ckeditor5/issues/541

1. Move deps to dev deps. Build should have no deps.
2. Move `ckeditor.js` to `src/ckeditor.js`.
3. Clean up the sample (https://github.com/ckeditor/ckeditor5/issues/535).

**Comment by Reinmar** [comment] 2017-09-14 11:26
Actually, it's more. Because not only we want to change the repository structure but also the npm package's content. See https://github.com/ckeditor/ckeditor5/issues/541#issuecomment-327215713

**Comment by fredck** [comment] 2017-09-14 15:27
> Move deps to dev deps. Build should have no deps.

Not sure this has been agreed, but anyway, I don't think it makes sense changing this.

In deps, we have the code which is referenced in the source code of the project. All the imports, usually

In dev-deps, we have the development stuff... things that don't have anything to do with the source code.

So I think we're doing this in the right way right now.

**Comment by Reinmar** [comment] 2017-09-14 15:31
> Not sure this has been agreed, but anyway, I don't think it makes sense changing this.

Did you read my comment https://github.com/ckeditor/ckeditor5/issues/541#issuecomment-327191768?

**Comment by Reinmar** [comment] 2017-09-14 15:32
> So I think we're doing this in the right way right now.

We're not. The package has no dependencies. The bundle doesn't need anything to work. And the npm package will contain only the bundle.

**Comment by fredck** [comment] 2017-09-14 15:38
Ha... I got your point... and that's because we're using the repo for two things at the same time... to hold the source code and to distribute the bundle. In reality, each should have their own package.json and be separate projects :/

Shouldn't the build folder contain a dedicated package.json then and that folder be the one we use to distribute the bundle in npm?

**Comment by fredck** [comment] 2017-09-14 15:40
Btw, did you read my comment :D
https://github.com/ckeditor/ckeditor5/issues/541#issuecomment-327196817

**Comment by fredck** [comment] 2017-09-14 15:43
In fact, the build folder IS the one published to npm and zipped. So it has to have its own package.json and the one that we use at the root of this repo has nothing to do with that.

**Comment by fredck** [comment] 2017-09-14 15:49
Btw, all this make think about this... should we include the `/build` folder inside this repo or .gitignore it? I don't think it makes sense having it here as all builds will be in npm.

**Comment by Reinmar** [comment] 2017-09-15 13:30
> Btw, all this make think about this... should we include the /build folder inside this repo or .gitignore it? I don't think it makes sense having it here as all builds will be in npm.

We may consider gitignoring it. But this means that you'll have a bit longer way to the first success after cloning this repo. I'm ok with both situations.

> In fact, the build folder IS the one published to npm and zipped. So it has to have its own package.json and the one that we use at the root of this repo has nothing to do with that.

We may have there a simple `package.json`. Then, the main one would be marked as "private". I'd also add `build/README.md` and `build/LICENSE.md` then. However, `CHANGELOG.md`, for instance, needs to be copied because it should also be in the main directory. So this is not that simple.

And there's more – if we'll change the structure of directories between repo and npm switching between npm and GH may be harder. We will depend on the "main" field of `package.json` though, so maybe it's enough.

Anyway, I'll look into this. I don't know if it's good to have two separate `package.json`s and if anyone is doing that. Basically, there's no problem with having the one available in the root directory to describe the package. The only reason to duplicate it may be to publish the right files to npm and to have the right structure.

I'll check what's the best way to do that.

**Comment by pomek** [comment] 2017-09-21 08:17
I am wondering whether we could add a `files` key to `package.json`.

When we install the build, we don't need to have all these files. I guess we could publish only the `build/` directory (and the basic files like README, CHANGELOG, package.json).

But if the build will not contain the `bin/` directory and `build-config.js` files, it will be hard to customize the build. WDYT?

**Comment by pomek** [comment] 2017-09-21 08:17
`sample/` directory should be published too (according to https://github.com/ckeditor/ckeditor5/issues/535#issuecomment-326894240).

**Comment by pomek** [comment] 2017-09-21 08:19
Hm. My bad, we have a `.npmignore` file which defined which files are ignored. So, ignore my comments.

**Comment by pomek** [comment] 2017-09-21 08:34
ATM I did the first and second points from the first post of the issue. The last point is waiting for an image to sample (https://github.com/ckeditor/ckeditor5/issues/535#issuecomment-331080210).

* https://github.com/ckeditor/ckeditor5-build-classic/compare/t/23
* https://github.com/ckeditor/ckeditor5-build-inline/compare/t/ckeditor5-build-classic/23
* https://github.com/ckeditor/ckeditor5-build-balloon/compare/t/ckeditor5-build-classic/23

**Comment by pomek** [comment] 2017-09-21 09:11
According to https://github.com/ckeditor/ckeditor5/issues/535#issuecomment-331091205, should we remove `sample/` directory from the repository? 

If no, let me know what I should change.

cc: @wwalc

**Comment by wwalc** [comment] 2017-09-21 11:16
Confirmed, let's remove samples.

**Comment by Reinmar** [comment] 2017-09-21 11:37
From the repo? Why. It does not make sense to publish it but it might help when rebuilding the editor in a cloned repo.

**Comment by pomek** [comment] 2017-09-27 06:40
Because we have two answers which denied each other, I would like to ask one more time – what should I do with the `sample/` directory?

**Comment by Reinmar** [comment] 2017-09-27 07:59
The directory should be kept in the repo but must not be published.

**Comment by pomek** [comment] 2017-09-27 13:06
I would like to add a comment regarding to the second part of the issue:

> Actually, it's more. Because not only we want to change the repository structure but also the npm package's content. See ckeditor/ckeditor5#541 (comment)

I've checked a few packages and I would like to share with the conclusions:

- [`pug-runtime`](https://www.npmjs.com/package/pug-runtime) publishes two different things. On GH we have the whole repository, on the NPM we have dedicated build which is made before the publishing (https://github.com/pugjs/pug/tree/master/packages/pug-runtime),
- [`socket.io`](https://www.npmjs.com/package/socket.io) publishes the `lib/` directory only (https://github.com/socketio/socket.io). 
- Socket client – [`socket.io-client`](https://www.npmjs.com/package/socket.io-client) publishes the `lib/` and `dist/` directories (https://github.com/socketio/socket.io-client),
- [`sizzle`](https://www.npmjs.com/package/sizzle) (engine selector from jQuery) publishes only the `dist/` directory. The `main` key in `package.json` references to the file in `dist/` directory (https://github.com/jquery/sizzle).

---

As a short summary, I can say that common practice is having the `dist/` directory published on NPM and the whole repository published on GH.

**Comment by Reinmar** [comment] 2017-09-27 15:04
OK, socket.io and sizzle publish exactly the same readme using the root package.json. pug-runtime have a complicated release script which I don't want to work on and maintain.

Also, we need to consider the fact that our main release tools should not need to know about how builds need to be published. And, for instance, they are doing `npm version` directly in the root of the repository. So, we should have just one `package.json`, which means also one `README`, etc.

So, let's do the real minimum here:

* `main` filed already points to `./build/ckeditor.js` which is fine,
* let's add `files` field to `package.json`s,
* and that's actually it.

This is the least we can do which is also what we should do.

**Closed** 2017-09-28 12:07 UTC
Labels: status:confirmed, type:task
